version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:Yougotthis%4099@db:5432/trades_db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Yougotthis@99
      POSTGRES_DB: trade_order_details
    ports:
      - "5432:5432"
