name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Copy files to EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}         
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}   
          source: "./"
          target: "/home/ubuntu/trade-app"

      - name: Execute deployment commands on EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/trade-app
            sudo docker-compose down
            sudo docker-compose up -d --build
